# Generated by Django 2.2.5 on 2021-02-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreviewarticle',
            name='introduction',
            field=models.CharField(default='*Introduction*', max_length=2000),
        ),
        migrations.AlterField(
            model_name='bookreviewarticle',
            name='review_content',
            field=models.CharField(max_length=25000),
        ),
    ]
