# Generated by Django 2.2.5 on 2021-02-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_reviews', '0002_auto_20210217_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreviewarticle',
            name='book_tags',
        ),
    ]
