# Generated by Django 2.2.5 on 2020-11-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookReviewArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=64)),
                ('book_tags', models.CharField(choices=[('misc', 'miscellaneous'), ('', ''), ('', ''), ('', '')], default='misc', max_length=32)),
                ('review_content', models.CharField(max_length=5000)),
                ('article_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
