# Generated by Django 2.2.5 on 2021-02-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thoughtarticles',
            name='introduction',
            field=models.CharField(default='*Introduction*', max_length=2000),
        ),
    ]
